"""empty message

Revision ID: 63c4c664cd45
Revises: 968b8c4e00bd
Create Date: 2017-09-30 17:28:10.966377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c4c664cd45'
down_revision = '968b8c4e00bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('time', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'time')
    # ### end Alembic commands ###
